config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :matches
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "matches#index"
  resources :projects
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    #can :manage, :all
    if user.admin_role?
      can :manage, :all
      can :access, :rails_admin
      can :manage, :dashboard
    end
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/match.rb
class Match < ApplicationRecord
    validates_presence_of :opponent, :location, :score
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :authenticate_user!
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ new edit create update destroy]
  # GET /matches or /matches.json
  def index
    @matches = Match.all
  end

  # GET /matches/1 or /matches/1.json
  def show
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches or /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to match_url(@match), notice: "Match was successfully created." }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1 or /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to match_url(@match), notice: "Match was successfully updated." }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1 or /matches/1.json
  def destroy
    @match.destroy

    respond_to do |format|
      format.html { redirect_to matches_url, notice: "Match was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def match_params
      params.require(:match).permit(:opponent, :score, :location, :notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cs3300project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <style>
    .title {
      color: white;
      font_size: 300%;
    }

  </style>
<style type="text/css">
  body {background: lightblue !important;}
</style>

  <body>
  <nav class='navbar' style ="background-color: green;">
    <div class="nav navbar-nav navbar-center">
      <a class="navbar-brand mb-0 title" href="#">Tennis Matches</a>
    </div>
      <div class="float-right">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <% if current_user.admin_role %>
          <div class='btn-group'> <%= link_to "Admin Dashboard", rails_admin_path, :class => "btn btn-dark" %> </div>
        <% end %>
        <div class='btn-group'> <%= link_to 'Edit profile', edit_user_registration_path, :class => "btn btn-dark" %> </div> |
        <div class='btn-group'> <%= link_to 'Logout', destroy_user_session_path, method: :delete, :class => "btn btn-dark" %> </div>
      <% else %>
        <div class='btn-group'> <%= link_to "Sign up", new_user_registration_path, :class => "btn btn-dark" %> </div> |
        <div class='btn-group'> <%= link_to "Login", new_user_session_path, :class => "btn btn-dark" %> </div>
      <% end %>
      </div>
  </nav>
  <p class="notice"><%= notice %></p> 
  <p class="alert"><%= alert %></p> 
    <%= yield %>
  </body>
</html>

app/views/matches/_form.html.erb
<%= form_with(model: match) do |form| %>
  <% if match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
        <% match.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class='container' style='text-align:center'>
    <div class="field">
      <%= form.label :opponent, :style => "font-size: 150%" %>
      <br>
      <%= form.text_field :opponent %>
    </div>

    <div class="field">
      <%= form.label :score, :style => "font-size: 150%" %>
      <br>
      <%= form.number_field :score %>
    </div>

    <div class="field">
      <%= form.label :location, :style => "font-size: 150%" %>
      <br>
      <%= form.text_area :location %>
    </div>

    <div class="field">
      <%= form.label :notes, :style => "font-size: 150%" %>
      <br>
      <%= form.text_area :notes %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  </div>
<% end %>

app/views/matches/edit.html.erb
<div class='container' style='text-align:center'>
    <h1>Editing Match</h1>
</div>

<br>
<%= render 'form', match: @match %>
<div class='container' style='text-align:center'>
<div class='btn-group'><%= link_to 'Show', @match, :class => "btn btn-outline-primary" %></div> |
<div class='btn-group'><%= link_to 'Back', matches_path, :class => "btn btn-outline-primary" %></div>
</div>

app/views/matches/index.html.erb
<div class='container' style="text-align:center">
  <h1 style="font_size:250%">Recorded Matches:</h1>
</div>
<div class="container" style = "border:3px outset black;">
  <table>
    <thead>
      <tr>
        <th style="font-size:125%">Opponent</th>
        <th></th>
        <th style="font-size:125%">Score</th>
        <th></th>
        <th style="font-size:125%">Location</th>
        <th></th>
        <th style="font-size:125%">Notes</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @matches.each do |match| %>
        <tr>
          <td><%= match.opponent %></td>
          <td></td>
          <td><%= match.score %></td>
          <td></td>
          <td><%= match.location %></td>
          <td></td>
          <td><%= match.notes %></td>
          <td><div class='btn-group'><%= link_to 'Show', match, :class => "btn btn-outline-primary" %></div></td>
          <% if user_signed_in? %>
          <td><div class='btn-group'><%= link_to 'Edit', edit_match_path(match), :class => "btn btn-outline-primary" %></div></td>
          <td><div class ='btn-group'><%= link_to 'Destroy', match, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-outline-primary" %></div></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>
<div class='container' style="text-align:center">
  <% if user_signed_in? %>
    <div class='btn-group'><%= link_to 'New Match', new_match_path, :class => "btn btn-outline-secondary" %> </div>
  <% end %>
</div>

app/views/matches/new.html.erb
<div class='container', style="text-align:center">
    <h1>New Match</h1>
</div>

<br>
<%= render 'form', match: @match %>
<div class='container' style='text-align:center'>
<div class='btn-group'><%= link_to 'Back', matches_path, :class => "btn btn-outline-primary" %></div>
</div>

app/views/matches/show.html.erb
<p id="notice"><%= notice %></p>
<body>
<div class='container' style='text-align:center'>
  <h1> Match Details </h1>
</div>

<br>

<div class='container' style='text-align:center'>
  <p>
    <strong>Opponent:</strong>
    <%= @match.opponent %>
  </p>

  <p>
    <strong>Score:</strong>
    <%= @match.score %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= @match.location %>
  </p>

  <p>
    <strong>Notes:</strong>
    <%= @match.notes %>
  </p>

  <div class='btn-group'><%= link_to 'Edit', edit_match_path(@match), :class => "btn btn-outline-primary" %></div> |
  <div class='btn-group'><%= link_to 'Back', matches_path, :class => "btn btn-outline-primary" %> </div>

</div>
</body>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>